### PR TITLE
python algorithms

### PR DESCRIPTION
**Pull request by prernadabi23**

### CODE REVIEW

**Review by suryapratapsinghsuryavanshi — CHANGES_REQUESTED** [review]
I can not find the output of your program please make sure the code is properly written.

**Comment by prernadabi23** [comment]
you have to give input then it will give output.

**Comment by prernadabi23** [comment]
i have added new files.

**Review by suryapratapsinghsuryavanshi — APPROVED** [review]

**Comment by suryapratapsinghsuryavanshi** [comment]
Thanks for your contribution. @prernadabi23

**Pull request merged**
